### ISSUE TITLE
1st feedback for website

### ISSUE THREAD

**Issue by dune73** [coreruleset/website#5]
I tried to get a working hugo setup high enough to serve the new website. After 1h of trying I give up and provide my feedback via issue instead of PR. Sorry.

### Front
- [x] OWASP \\ CRS PROJECT. better: OWASP CRS \\ PROJECT
- [x] The first line of defense. better: The 1st Line of Defense
- Latest Blog Posts
  * [x] title should not be black I think. Better slight grey or blueish (Fixed in #11)
  * [x] bullet points are too mugh left (Fixed in #11)
- Call for sponsors
  * [x] better use my owasp email address. The coreruleset.org one is never used elsewhere and I would not notice if it fails working. (Fixed in #11)
- Sponsors
  * [x] V-align USP and Google (Fixed in #15 )
  * [x] Resize Swiss Post to a reasonable level (Fixed in #15 )
### Footer
- * [x] I would not use black as background. White like the header is probably better (Attempt at #8)
### Blog
- * [x] This brings 2 categories, news and portraits. Everything else does not seem to be accessible with beyond the last 3 items on the front page. (Attempt in #12)
- https://coreruleset.github.io/website/support/
  * [x] Carries a link "sponsorship of NGINX". This is broken.
        https://coreruleset.github.io/20210305/announcing-a-partnership-with-nginx/
        should be
        https://coreruleset.github.io/website/2021/03/05/announcing-a-partnership-with-nginx/ (Fixed in #10)
   * [x] Also wrong in content/blog/2021-04-14-introducing-the-dev-on-duty-program.md (Fixed in #10)
   * [x] And in content/blog/2021-03-05-announcing-a-partnership-with-nginx.md (Fixed in #10)
- * [x] In all the blog posts, there is a field "permalink". This seems to carry a different date format than the one actually used in the URI. 2022-09-20 vs 2022/09/22/ (Fixed in #9)
- * [x] The same problem is present in another 40+ instances. Get them via: `grep -r 20[12][0-9][01][0-9][01][0-9] * 2>/dev/null | grep -v json | grep -v .js | grep -v hugo-extended | grep -v permalink`. (Fixed in #9)

**Comment by fzipi** [comment]
### General comments

- Call for sponsors: I would try not to use personal addresses in the future. While you normally represent us for sponsoring, better maybe to create an alias (like sponsorship@coreruleset.org) in the email setup (when we move way from slik.nl) that forwards things. For now I'll add your owasp email.
- Footer: you meant "not dark" instead of white, right?
- Blog: here I just listed some of the tags we have in our blogs to be more relevant. you can always go to the full list...
- Permalinks: probably removing them is the way to go

**Comment by dune73** [comment]
* Sponsor email: good thinking
* Footer: Anything but the black currently set. I think the color of the topbar would be good
* Blog: The full list does not work for me. No full list when I click on "Blog"
* Permalinks: Yes, that would make sense if we can keep the original URI

**Comment by fzipi** [comment]
Feedback addressed, closing.
